
# Generated by Django 4.2.5 on 2023-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_empl'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=30)),
                ('speed', models.IntegerField(default=50)),
                ('carmodel', models.CharField(max_length=30)),
            ],
        ),
    ]
